// src/agents/chart.tool.ts

export interface ChartConfig {
  type: string;
  data: {
    labels: string[];
    datasets: { label?: string; data: number[] }[];
  };
  options?: Record<string, unknown>;
}

export class ChartTool {
  /**
   * Mocked Chart.js config generator.
   * Returns a fixed bar-chart configuration as required by the task.
   */
  async run(_input: string): Promise<ChartConfig> {
    return {
      type: 'bar',
      data: {
        labels: ['Jan', 'Feb', 'Mar'],
        datasets: [
          {
            label: 'Sample Dataset',
            data: [10, 20, 30],
          },
        ],
      },
      options: {
        responsive: true,
        plugins: {
          legend: { position: 'top' },
          title: { display: true, text: 'Chart generated by Chart.js Tool' },
        },
      },
    };
  }
}